on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # TODO: change to v2 as it's available
    - uses: actions/checkout@v2
    # Include asciidoctor-action and run the cli tool
    - uses: mgred/asciidoctor-action@master
      with:
        # TODO: this should fail on README.adoc not found
        args: asciidoctor README.adoc
